### ISSUE TITLE
Managing the left navigation

### ISSUE THREAD

**Issue by harikt** [auraphp/auraphp.github.com#13]
When newer versions come, and newer languages are added how do we plan to manage the left navigation.

Currently the layout is docs

```html
---
layout: site
---
<div class="row-fluid">
  <div class="span3">{% include manuals/en/v1/contents.html %}</div>
  <div class="span9">{{ content }}</div>
</div>
```

And we can see the left navigation is fixed. May be we need to find a way how we can make the left nav dynamic.

One way is add a variable in the markdown and use version, language.

**Comment by pmjones** [comment]
Hey @harikt , any further thoughts on this one?

(I know how you hate long-standing issues and PRs. ;-)

**Comment by harikt** [comment]
Already solved via having different layouts. https://github.com/auraphp/auraphp.github.com/tree/master/_layouts . Not sure whether it is right or wrong. ( See http://auraphp.com/manuals/2.0/ja/ )

Interested to hear it :) .

**Comment by pmjones** [comment]
> Already solved via having different layouts.

Sweet -- so we can close this?

**Comment by harikt** [comment]
for the current being, if there is no better ways :) .
