### ISSUE TITLE
Japanese Translation for v2

### ISSUE THREAD

**Issue by koriym** [auraphp/auraphp.github.com#52]
task list for manuals/2.0/ja

- [x] configuration.md @shingo-kumagai
- [x] cli.md **@jingu**
- [x] di.md @koriym
- [x] dispatcher.md @zukimochi 
- [x] forms.md @yutakachiba
- [x] index.md @tdakak
- [x] intl.md @okapon 
- [x] quick-start.md @yutakachiba
- [x] request.md @yutakachiba
- [x] response.md  @koriym
- [x] router.md @shingo-kumagai 
- [x] session.md  @kumamidori
- [x] setup.md @kenjis
- [x] view.md @shingo-kumagai

Let's collaborate and we don't duplicate the same work.

このissueを作業が被らないように使います。マークが入っているのが翻訳終了したもので、これから（または現在）自分が担当するページをここでコメントしてください。よろしくお願いします。

**Comment by koriym** [comment]
ping @kumamidori @shingo-kumagai @jingu @okapon@yutakachiba @zukimochi

**Comment by koriym** [comment]
ping @tadaaki @kenjis @brtriver

**Comment by okapon** [comment]
私`intl.md`翻訳作業中ですー

**Comment by kumamidori** [comment]
assign session.md  to kumamidori
（あと半分くらいで終わるのですが。PRは今週末になるかもしれません :sheep:  ）

**Comment by harikt** [comment]
@koriym I will say don't go for translating validation . Make use of v2 once it is released .

**Comment by koriym** [comment]
@harikt removed. thanks :)

**Comment by tdakak** [comment]
``index.md`` 作業中です。

**Comment by shingo-kumagai** [comment]
finished configuration.md. let me go view.md next.

**Comment by koriym** [comment]
@shingo-kumagai nice !

**Comment by harikt** [comment]
Good work guys! . 

I feel it is good not to take auth.md for it is still in beta. It is better to have nothing than wrong doc in the end.

**Comment by koriym** [comment]
@harikt right, I will remove auth.md also. Thank you for watching this issue. I am (also) glad you're sticking around ! cc/ @pmjones

**Comment by yutakachiba** [comment]
I'd like to translate request.md if no one translated it yet.

**Comment by koriym** [comment]
@yutakachiba chiba san, good to hear from you !
marked `request.md` as WIP.

**Comment by koriym** [comment]
@harikt ard.md is not liked from anywhere. Is it ?

**Comment by koriym** [comment]
I take `response.md` for next.

**Comment by kenjis** [comment]
I take `setup.md`.

**Comment by harikt** [comment]
@koriym may be we can look into the adr later. I am thinking it probably needs a better rewrite.

**Comment by koriym** [comment]
@harikt I see.

**Comment by koriym** [comment]
hi @kenjis, nice to see you here !

**Comment by harikt** [comment]
@koriym it may be good to not remove the names who have done the translations. It may help to know the contributors.

Thank you all. You all doing a great job. I appreciate your time and efforts.

**Comment by koriym** [comment]
@harikt Allright. I am actually thinking about it. :) (maybe I add the name to the section already done)

**Comment by harikt** [comment]
@koriym yes, ie good.

**Comment by koriym** [comment]
done !

**Comment by kenjis** [comment]
I would like to translate TOC into Japanese in left column on <http://auraphp.com/manuals/2.0/ja/>. Where do they come from?

**Comment by harikt** [comment]
@kenjis here you go https://github.com/auraphp/auraphp.github.com/blob/master/_includes/manuals/v2/ja/contents.html

**Comment by harikt** [comment]
@koriym copy https://github.com/auraphp/auraphp.github.com/blob/master/manuals/v1/ja/filter.md to validation.md . That can work for the current time.

**Comment by harikt** [comment]
@okapon Sorry the v1 version of https://github.com/auraphp/auraphp.github.com/blob/master/manuals/v1/ja/intl.md can be copied for they  are same. If you are done , no issues.

**Comment by koriym** [comment]
@harikt Ok, I will do it !

**Comment by harikt** [comment]
no one taking router.md ? It is one of the nice components.

**Comment by shingo-kumagai** [comment]
let me go router.md then!

**Comment by harikt** [comment]
@shingo-kumagai :+1:  . @koriym you may edit it then :) .

**Comment by koriym** [comment]
@shingo-kumagai :+1: nice @harikt done !

**Comment by tdakak** [comment]
I take `adr.md`.

**Comment by harikt** [comment]
@tdakak no. Don't convert for now. I need to look and verify it, probably some changes is needed. ie why not yet published in the english manual itself.

**Comment by tdakak** [comment]
@harikt I understand. Thank you for your comment.

**Comment by mackstar** [comment]
このプログレスはどうですか？

**Comment by koriym** [comment]
@mackstar あと２つ(@okaponさんと@shingo-kumagaiの分で）で終わりの予定です。

**Comment by harikt** [comment]
Hi guys, 

if you have send a PR and if its merged you are listed now at http://auraphp.com/community . If you find missing please report . 

Thank you

**Comment by koriym** [comment]
@shingo-kumagai just finished his work, He did three  ! Awsome. Arigato @shingo-kumagai san :)

**Comment by shingo-kumagai** [comment]
You're welcome :)

**Comment by koriym** [comment]
@okapon ping

**Comment by harikt** [comment]
@koriym if @okapon have not finished could you please check if v1 intl is same ? I believe it is same. Just need to check, and fix the permanent links.

Thank you.

**Comment by koriym** [comment]
@harikt no v1 intl manual ?

**Comment by kenjis** [comment]
I sent PR which add translation of some headings.

By the way, on http://auraphp.com/manuals/2.0/ja/request/, headings about object name are English like "Clinet", "Content", "Headers". But on http://auraphp.com/manuals/2.0/ja/response/, they are translated into Japanese. For example, "Headers" -> "ヘッダー".

To translate them or not, which is better?

**Comment by harikt** [comment]
@kenjis good call. In 2 minds. Lets translate for there is already an English version if needed to check :) .

**Comment by harikt** [comment]
@koriym I see :) . You are right there is none seen :( .

**Comment by koriym** [comment]
@okapon さんの分が途中までですが一旦mergeしました。

**Comment by koriym** [comment]
Over ! Nice work, Thanks all !
