### ISSUE TITLE
Change the ash color

### ISSUE THREAD

**Issue by harikt** [auraphp/auraphp.github.com#76]
Hi Paul, 

This ash color have been for quite some time. What about changing the color of theme ?

![blue](https://cloud.githubusercontent.com/assets/120454/6991055/f11ebf6e-da9c-11e4-89ac-b4c915c0ba6a.png)

What do you think on this ?

**Comment by harikt** [comment]
Another iteration I tried

![with-red](https://cloud.githubusercontent.com/assets/120454/6991107/82a2fc46-da9f-11e4-9326-326b11a7ee9c.png)

the below is only change in navigation.

![with-red](https://cloud.githubusercontent.com/assets/120454/6991098/0a1b08ae-da9f-11e4-99b7-9fe855fef0bf.png)

**Comment by harikt** [comment]
Adding current one also in this , so can be viewed 

![current](https://cloud.githubusercontent.com/assets/120454/6991115/da0e0656-da9f-11e4-9040-d42d12299836.png)

**Comment by pmjones** [comment]
I don't see a problem with the current color. If you want to send a PR that, say, updates the entire theme to a newer version of Bootstrap etc., I can review.

**Comment by koriym** [comment]
![2015-04-04 11 43 36](https://cloud.githubusercontent.com/assets/529021/6991181/e95de066-dabf-11e4-9c51-9ebcc15958b9.png)

This is not a proposal. 
Just wanted to share how the impression will be changed when we change the design totally.

**Comment by harikt** [comment]
> I don't see a problem with the current color. 

ok.

> If you want to send a PR that, say, updates the entire theme to a newer version of Bootstrap etc., I can review.

Idea was to show you first, and if you like can send a PR. As you didn't liked both the iterations, and is ok with the current one. I am ok for closing the same.

By the way Good one @koriym , though I don't like the dark color. Which one did you tried ? Is it bootstrap or may be a link to the theme ?

**Comment by koriym** [comment]
@harikt Just edited at http://site120510-3715-9848.strikingly.com/ to see the image. (so it's not proposal or PR)

**Comment by harikt** [comment]
Thank you @koriym .

**Comment by pmjones** [comment]
@koriym Dude that is *gorgeous*.
