### ISSUE TITLE
Router version 3.0.0‑alpha2

### ISSUE THREAD

**Issue by harikt** [auraphp/auraphp.github.com#78]
The website  http://auraphp.com/ currently lists 3.0.0‑alpha2 , but beta already released.

**Comment by harikt** [comment]
Is this a manual edit for the file https://github.com/auraphp/auraphp.github.com/blob/master/packages.json ?

**Comment by pmjones** [comment]
Ah, it's a sorting issue. Using arsort() instead of a user-sort with version_compare(). Will update. Thanks!

**Comment by pmjones** [comment]
Fixed!
